env:
  RCLONECONFIG_DRIVE: "ENCRYPTED[75f8315cb76f92058ed16b6c7f10fa791852aefb211e35e7042a1bd875a06c676dc5e0f85e616b3033ba2ddd25e71b9c]"
  TG_TOKEN: "ENCRYPTED[e65eea567a2b6f6b13d70a689f09786e5ce19d03f5cce4e6a98ca210fca09ab3d59e46c6eae3a7971f2051629d012708]"
  TG_CHAT_ID: "ENCRYPTED[6d4ef793f96a1d28d641983a5f3a54288790f59eb799c1f17d4abc3fc7fe21289ea69eaf98b5b0c340a2b14164d19cb1]"
  WORKDIR: "/tmp"
  EMAIL: "ENCRYPTED[351f1b6cb9169531b1947292700e454026ce23770d79a4bc64cb0aafd9e90cf90792be5f551e343ac2a506d4720605ea]"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'Tiktodz'
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Load-Ccache_background_script:
     - ./script/load_ccache.sh

  Sync-rom_script:
     - ./script/sync.sh
     
  Build-rom_script:
     - ./script/building.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./script/ziping.sh
