env:
  RCLONECONFIG_DRIVE: "ENCRYPTED[bc38b7459f528c621235c9d73df07e5d6ee7cb153dc4c7a189a070290c8d36e3612234d0b6f9f9da852357e9e05cbefa]"
  TG_TOKEN: "ENCRYPTED[!9dd7dd586d4a529588ae2eb6284ed41c303cfee5c1ffd8b9f8016bf3f8a5ffca0959da2b47bb85756cfbb36bc286474c!]"
  TG_CHAT_ID: "ENCRYPTED[!0039c8161abbb6fb6065e86eab02fbf4435203735f76757e0430d6c28ab8aa15701b0397cc16d0251b987c8a93893286!]"
  WORKDIR: "/tmp"
  EMAIL: "ENCRYPTED[!5469f2317419904fc4b423f7237ca70ea0e6e919d8348bd15def1f568fcb6a023ca7a88a2859dc6e2d6497d01a9c7d9f!]"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'NFS-Project'
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Load-Ccache_background_script:
     - ./script/load_ccache.sh

  Sync-rom_script:
     - ./script/sync.sh
     
  Build-rom_script:
     - ./script/building.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./script/ziping.sh
